"""

Parse miRDeep2 outputs to combine all samples into one file.

"""

import glob
import pandas as pd
import os
from functools import reduce

# Find paths for files needing to be parsed.
data_path = "miRDeep2_output/"


def parse_miRDeep2(data_path, out_path):
    
    miRDeep2_count_files = glob.glob(data_path + "/miRNAs_expressed_all_samples*", recursive=True)
    data = []
    
    for csv in miRDeep2_count_files:
        frame = pd.read_csv(csv, sep = "\t", usecols=["#miRNA", "total"])
        
        # This extracts the filename from the folder name generated by Unitas and renames counts column
        file_name = os.path.basename(csv).split("_", 4)[4]
        
        # Collapse identical rows and sum.
        frame = frame.rename(columns = {"#miRNA": "miRNAs", "total": "Raw_counts_" + file_name})
        frame = frame.groupby(["miRNAs"], as_index=False).agg({"Raw_counts_" + file_name: "sum"})
        data.append(frame)
        
    df_merged = reduce(lambda  left,right: pd.merge(left,right,on=["miRNAs"], how="outer"), data)
    df_merged.to_csv(out_path, index = False, na_rep = "NA")

parse_miRDeep2(snakemake.input[1], snakemake.output[0])