"""

Parse miRDeep2 outputs to combine all samples into one file.

"""

import glob
import pandas as pd
import os
from functools import reduce

# Combined miRDeep2 csv count outputs.

def parse_miRDeep2(out_path, myparam):
    
    miRDeep2_count_files = glob.glob(myparam + "miRNAs_expressed_all_samples*", recursive=True)
    data = []
    
    for csv in miRDeep2_count_files:
        frame = pd.read_csv(csv, sep = "\t", usecols=["#miRNA", "total"])
        
        # This extracts the filename from the folder name generated by Unitas and renames counts column
        file_name = os.path.basename(csv).split("_", 4)[4]
        
        # Collapse identical rows and sum.
        frame = frame.rename(columns = {"#miRNA": "miRNAs", "total": "Raw_counts_" + file_name})
        frame = frame.groupby(["miRNAs"], as_index=False).agg({"Raw_counts_" + file_name: "sum"})
        data.append(frame)
        
    df_merged = reduce(lambda  left,right: pd.merge(left,right,on=["miRNAs"], how="outer"), data)
    df_merged.to_csv(out_path[0], index = False, na_rep = "NA")

parse_miRDeep2(snakemake.output, snakemake.config["input_dir"])